apiVersion: v1
kind: PersistentVolume
metadata:
  name: iso-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/iso"
    type: DirectoryOrCreate