apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso-claim
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual