apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: virtualboxvms.myinfra.org
spec:
  compositeTypeRef:
    apiVersion: myinfra.org/v1alpha1
    kind: VirtualBoxVM
  resources:
    - name: virtualbox-vm
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: create-vm-
              spec:
                template:
                  spec:
                    containers:
                    - name: create-vm
                      image: python:3.10
                      command: ["python", "/scripts/create_vm.py"]
                      args: ["$(VM_NAME)", "$(VM_MEMORY)", "$(VM_CPUS)", "$(ISO_FILENAME)"]
                      env:
                      - name: VM_NAME
                        valueFrom:
                          resourceFieldRef:
                            fieldPath: metadata.name
                      - name: VM_MEMORY
                        valueFrom:
                          resourceFieldRef:
                            fieldPath: spec.vmMemory
                      - name: VM_CPUS
                        valueFrom:
                          resourceFieldRef:
                            fieldPath: spec.vmCpus
                      - name: ISO_FILENAME
                        valueFrom:
                          resourceFieldRef:
                            fieldPath: spec.isoFilename
                      volumeMounts:
                      - name: scripts
                        mountPath: /scripts
                      - name: iso-storage
                        mountPath: /data/iso
                    volumes:
                    - name: scripts
                      configMap:
                        name: vbox-scripts
                    - name: iso-storage
                      persistentVolumeClaim:
                        claimName: iso-claim
                    restartPolicy: Never