apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: virtualboxvms.myinfra.org
spec:
  group: myinfra.org
  names:
    kind: VirtualBoxVM
    plural: virtualboxvms
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                memory:
                  type: integer
                cpus:
                  type: integer
                isoPath:
                  type: string
              required:
                - memory
                - cpus
                - isoPath
