apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: virtualboxvms.myinfra.org
  labels:
    provider: virtualbox
spec:
  compositeTypeRef:
    apiVersion: myinfra.org/v1alpha1
    kind: VirtualBoxVM
  resources:
    - name: virtualbox-vm
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: create-vm-
              spec:
                template:
                  spec:
                    containers:
                    - name: create-vm
                      image: curlimages/curl
                      command: ["/bin/sh", "/scripts/create_vm.sh"]
                      env:
                      - name: VM_NAME
                        value: "{{ .composite.metadata.name }}"
                      - name: VM_MEMORY
                        value: "{{ .composite.spec.memory }}"
                      - name: VM_CPUS
                        value: "{{ .composite.spec.cpus }}"
                      - name: ISO_PATH
                        value: "{{ .composite.spec.isoPath }}"
                      volumeMounts:
                      - name: scripts
                        mountPath: /scripts
                    restartPolicy: Never
                    volumes:
                    - name: scripts
                      configMap:
                        name: vbox-api-script
