url: https://argoproj.github.io/argo-helm
chart: argo-cd
version: 7.8.13
values:
  global:
    domain: argocd.129.212.195.186.nip.io
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
