apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualboxvm-admin
rules:
- apiGroups: ["myinfra.org"]
  resources: ["virtualboxvms"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]