apiVersion: batch/v1
kind: Job
metadata:
  name: create-virtualbox-vm
spec:
  template:
    spec:
      containers:
      - name: create-vm
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
        - |
          curl -X POST http://172.21.192.1:5000/create_vm \
            -H "Content-Type: application/json" \
            -d '{
              "name": "test-vm",
              "memory": 2048,
              "cpus": 2,
              "iso_path": "ubuntu-24.04-live-server-amd64.iso"
            }'
      restartPolicy: Never
  backoffLimit: 4