apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: virtualboxvms.myinfra.org
spec:
  compositeTypeRef:
    apiVersion: myinfra.org/v1alpha1
    kind: VirtualBoxVM
  resources:
    - name: virtualbox-vm
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: create-vm-
                namespace: default
              spec:
                template:
                  spec:
                    containers:
                    - name: create-vm
                      image: curlimages/curl
                      command: ["/bin/sh", "-c"]
                      args:
                      - |
                        echo "Creating VM with the following parameters:"
                        echo "Name: {{ .composite.metadata.name }}"
                        echo "Memory: {{ .composite.spec.memory }} MB"
                        echo "CPUs: {{ .composite.spec.cpus }}"
                        echo "ISO Path: {{ .composite.spec.isoPath }}"
                        curl -v -X POST http://172.21.192.1:5000/create_vm \
                          -H "Content-Type: application/json" \
                          -d '{
                            "name": "{{ .composite.metadata.name }}",
                            "memory": {{ .composite.spec.memory }},
                            "cpus": {{ .composite.spec.cpus }},
                            "iso_path": "{{ .composite.spec.isoPath }}"
                          }' || echo "Curl command failed"
                    restartPolicy: Never
          providerConfigRef:
            name: kubernetes-provider
