apiVersion: v1
kind: ConfigMap
metadata:
  name: vbox-api-script
  namespace: crossplane-system
data:
  create_vm.sh: |
    #!/bin/sh
    curl -X POST http://172.21.192.1:5000/create_vm \
      -H "Content-Type: application/json" \
      -d '{
        "name": "'$VM_NAME'",
        "memory": '$VM_MEMORY',
        "cpus": '$VM_CPUS',
        "iso_path": "'$ISO_PATH'"
      }'