apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: virtualbox-workspace
spec:
  forProvider:
    source: Inline
    module: |
      {{ .Files.Get "files/terraform-modules/virtualbox/virtualbox-vm.tf" | nindent 8 }}
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: virtualbox-creds